pipeline{
   agent any
   tools{
    maven 'M2_HOME'
   }
   stages{
    stage("maven"){
        steps{
        sh 'mvn clean' 
        sh 'validate' 
        sh 'compile' 
        sh 'install' 
        sh 'test' 
        sh 'package'
        }
    }
    stage('upload artifact'){
        steps{
            sh 'curl -uadmin:AP8gcgmmset5jeYChTJYDN6XmDd -T \
            target/bio*.jar \
            "http://ec2-100-26-120-34.compute-1.amazonaws.com:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"'
        }
    }
   }
}